name: Tests

on:
  push:
    branches:
      - psycopg-dev
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container: python:3.10
    name: Test ${{ matrix.psycopg }} on ${{ matrix.backend }}

    continue-on-error: true
    strategy:
      matrix:
        psycopg: ["psycopg", "psycopg[binary]", psycopg2]
        backend: [postgis, postgres]

    services:
      postgres:
        image: postgis/postgis:14-3.2
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: python -m pip install -r tests/requirements/py3.txt -e .
      - run: python -m pip install ${{ matrix.psycopg }}
      - run: apt-get -y update && apt-get -y --no-install-recommends install gdal-data gdal-bin
      - name: Run tests
        run: cd tests && python runtests.py --settings=test_${{ matrix.backend }}
